name: e2e-automatic-trigger-tests
on: [push]

jobs:
  e2e-system-tests:
    runs-on: ubuntu-latest
    strategy:
      #max-parallel: 3
      fail-fast: false
      matrix:
        spec:
          [
            'account',
            'addons',
            'courses',
            'dashboard',
            'files',
            'help',
            'login',
            'management',
            'news',
            'tasks',
            'team',
            'topic'
          ]
    timeout-minutes: 5

    steps:
      - name: 🔔🔔🔔 Checkout 🔔🔔🔔
        uses: actions/checkout@v3

      - name: 🗑 Clean up previous report 🗑
        uses: cypress-io/github-action@v5
        with:
          command: npm run pretest

      - name: 🧪 Cypress run 🧪
        uses: cypress-io/github-action@v5
        timeout-minutes: 3
        env:
          CYPRESS_BRB: ${{ secrets.CYPRESS_BRB }}
          CYPRESS_NBC: ${{ secrets.CYPRESS_NBC }}
          CYPRESS_DEFAULT: ${{ secrets.CYPRESS_DEFAULT }}
          CYPRESS_TEACHER_1_EMAIL: ${{ secrets.CYPRESS_TEACHER_1_EMAIL }}
          CYPRESS_TEACHER_1_PASSWORD: ${{ secrets.CYPRESS_TEACHER_1_PASSWORD }}
          CYPRESS_TEACHER_2_EMAIL: ${{ secrets.CYPRESS_TEACHER_2_EMAIL }}
          CYPRESS_TEACHER_2_PASSWORD: ${{ secrets.CYPRESS_TEACHER_2_PASSWORD }}
          CYPRESS_STUDENT_1_EMAIL: ${{ secrets.CYPRESS_STUDENT_1_EMAIL }}
          CYPRESS_STUDENT_1_PASSWORD: ${{ secrets.CYPRESS_STUDENT_1_PASSWORD }}
          CYPRESS_STUDENT_2_EMAIL: ${{ secrets.CYPRESS_STUDENT_2_EMAIL }}
          CYPRESS_STUDENT_2_PASSWORD: ${{ secrets.CYPRESS_STUDENT_2_PASSWORD }}
          CYPRESS_ADMIN_1_EMAIL: ${{ secrets.CYPRESS_ADMIN_1_EMAIL }}
          CYPRESS_ADMIN_1_PASSWORD: ${{ secrets.CYPRESS_ADMIN_1_PASSWORD }}
          CYPRESS_EXPERT_1_EMAIL: ${{ secrets.CYPRESS_EXPERT_1_EMAIL }}
          CYPRESS_EXPERT_1_PASSWORD: ${{ secrets.CYPRESS_EXPERT_1_PASSWORD }}
          CYPRESS_STUDENT_EXTERN: ${{ secrets.CYPRESS_STUDENT_EXTERN }}
          CYPRESS_STUDENT_EXTERN_PASSWORD: ${{ secrets.CYPRESS_STUDENT_EXTERN_PASSWORD }}
          DEBUG: '@cypress/github-action'
        with:
          command: npm run tag:stable:${{ matrix.spec }}

      - name: 📬 Upload test artifacts 📬
        uses: actions/upload-artifact@v3
        if: always()
        with:
          if-no-files-found: error
          name: artifacts
          path: |
            ${{ github.workspace }}/cypress/cucumber-json/
            ${{ github.workspace }}/cypress/.run/
            ${{ github.workspace }}/cypress/videos/features
            ${{ github.workspace }}/cypress/screenshots

  generate-and-upload-report:
    runs-on: ubuntu-latest
    needs: e2e-system-tests
    if: always()

    steps:
      - name: 🔔🔔🔔 Checkout 🔔🔔🔔
        uses: actions/checkout@v3

      - name: 📩 Download reports artifacts 📩
        uses: actions/download-artifact@v3
        if: always()
        with:
          name: artifacts
          path: ${{ github.workspace }}/cypress/

      - name: 🚀 Generate Report 🚀
        uses: cypress-io/github-action@v5
        if: always()
        with:
          command: npm run generate:report

      - name: 🎉 Upload Report 🎉
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: my-report
          path: ${{ github.workspace }}/cypress/reports

      - name: 📼 Upload Video Artifact 📼
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: my-video-artifact
          path: ${{ github.workspace }}/cypress/videos/features
          retention-days: 3
