name: e2e-automatic-trigger-tests
on: [push]

jobs:
  e2e-system-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setting working directory
        working-directory: e2e-system-tests
        run: |
          pwd
          echo "${{ github.workspace }}"

      - name: Checkout
        uses: actions/checkout@v3
      #   with:
      #     repository: hpi-schul-cloud/e2e-system-tests
      #     ref: BC-4569-secrets-from-1pass-instead-of-github
      # path: e2e-system-tests

      - name: Check dir
        run: |
          pwd
          echo "${{ github.workspace }}"

      - name: Calling reusable workflow
        uses: ./.github/workflows/main.yml@BC-4569-secrets-from-1pass-instead-of-github
        with:
          secrets:
          service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}

      - name: Generate Report
        uses: cypress-io/github-action@v5
        if: always()
        with:
          command: npm run generate:report

      - name: Upload Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: my-report
          path: ${{ github.workspace }}/reports

      - name: Upload Video Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: my-video-artifact
          path: ${{ github.workspace }}/cypress/videos/
          retention-days: 3
