name: e2e-automatic-trigger-tests
on: [push]

jobs:
  e2e-system-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: BC-4569-secrets-from-1pass-instead-of-github

  configuring-loading-secrets-running-tests:
    uses: ./.github/workflows/main.yml
    secrets:
      service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}

  generating-and-uploading-report:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Report
        uses: cypress-io/github-action@v5
        if: always()
        with:
          command: npm run generate:report

      - name: Upload Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: my-report
          path: ${{ github.workspace }}/reports

      - name: Upload Video Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: my-video-artifact
          path: ${{ github.workspace }}/cypress/videos/
          retention-days: 3
