name: configure, load secrets, run Cypress tests, generate and upload reports
on:
  workflow_call:
    secrets:
      service-account-token:
        required: true
    inputs:
      cypress_brb:
        description: "brb url from the workflow"
        type: string
      cypress_nbc:
        description: "nbc url from the workflow"
        type: string
      cypress_dbc:
        description: "dbc url from the workflow"
        type: string
      tag:
        description: "tag for running cypress tests"
        type: string
      environment:
        description: "environment for retriving credentials from 1Password vault"
        type: string
      groups:
        description: "identifier to store test results, reports, and artifacts separately, preventing overwrites in parallel runs."
        type: string

jobs:
  configure-load-secrets-and-run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: hpi-schul-cloud/e2e-system-tests
          path: e2e-system-tests

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Verify 1Password was Installed
        run: op --version

      - name: Configure 1Password Service Account
        uses: 1password/load-secrets-action/configure@v1
        with:
          service-account-token: ${{ secrets.service-account-token }}

      - name: Fetch JSON files from 1Password
        run: |
          instances=(brb dbc nbc)

          for instance in "${instances[@]}"; do
              vault_name="cy-${{ inputs.environment }}-${instance}"
              op document get cypress-json --vault "$vault_name" --output ${{ github.workspace }}/e2e-system-tests/env_variables/file-${{ inputs.environment }}-${instance}.json
          done

      - name: Aggregate JSON Data into one File
        id: read_variables
        run: |
          workflow="${{ github.workflow }}"
          workspace_path="${{ github.workspace }}"

          chmod +x ${workspace_path}/e2e-system-tests/scripts/aggregate-json-files.sh
          ${workspace_path}/e2e-system-tests/scripts/aggregate-json-files.sh \
            "${workflow}" \
            "${{ inputs.cypress_brb }}" \
            "${{ inputs.cypress_dbc }}" \
            "${{ inputs.cypress_nbc }}" \
            "${workspace_path}" \
            "${{ inputs.environment }}"

      - name: Install Edge
        run: |
          sudo apt-get update
          sudo apt-get install -y microsoft-edge-stable
          sudo apt-get install -y libnss3 libatk-bridge2.0-0 libcups2 libxkbcommon-x11-0 dbus-x11
          microsoft-edge-stable --version

      - name: Clean up previous report
        uses: cypress-io/github-action@v5
        with:
          working-directory: e2e-system-tests
          command: npm run pretest
          browser: edge

      - name: Start Edge (Headless)
        run: |
          export DBUS_SESSION_BUS_ADDRESS=/dev/null
          nohup microsoft-edge-stable --headless --no-sandbox --remote-debugging-port=9222 > edge.log 2>&1 &
          # sleep 5
          # cat edge.log

      - name: Wait for Edge to Warm Up
        run: |
          n=0
          until curl -s http://localhost:9222/json | grep -q "WebSocketDebuggerUrl" || [ $n -ge 30 ]; do
            echo "Waiting for Edge to start..."
            n=$((n+1))
            sleep 1
          done
          if [ $n -ge 30 ]; then
            echo "Edge failed to start within 30 seconds"
            exit 1
          fi

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: e2e-system-tests
          command: npm run ${{ inputs.tag }}
          browser: edge

      - name: Generate Report
        if: always()
        working-directory: e2e-system-tests
        run: |
          npm run generate:report

      - name: Upload Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ inputs.groups }}-cypress-report
          path: ${{ github.workspace }}/e2e-system-tests/reports/

      - name: Upload Video Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ inputs.groups }}-cypress-video-artifact
          path: ${{ github.workspace }}/e2e-system-tests/cypress/videos/${{ inputs.groups }}
          retention-days: 3
