name: configure, load secrets, run Cypress tests, generate and upload reports
on:
  workflow_call:
    secrets:
      service-account-token:
        required: true
    inputs:
      cypress_brb:
        description: "brb url from remote workflow"
        type: string
      cypress_nbc:
        description: "nbc url from remote workflow"
        type: string
      cypress_default:
        description: "default url from remote workflow"
        type: string

jobs:
  configure-load-secrets:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.setting_url.outputs.TAG }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: hpi-schul-cloud/e2e-system-tests
          path: e2e-system-tests

      - name: Configure 1Password Service Account
        uses: 1password/load-secrets-action/configure@v1
        with:
          service-account-token: ${{ secrets.service-account-token }}

      - name: Setting URL's
        id: setting_url
        run: |
          workflow_name="${{ github.workflow }}"
          if [[ $workflow_name == *"manual"* ]]; then
            echo "This is a manual workflow"
            echo "CYPRESS_BRB=${{ github.event.inputs.instance1 }}" >> $GITHUB_ENV
            echo "$CYPRESS_BRB"
            echo "CYPRESS_NBC=${{ github.event.inputs.instance2 }}" >> $GITHUB_ENV
            echo "$CYPRESS_NBC"
            echo "CYPRESS_DEFAULT=${{ github.event.inputs.instance3 }}" >> $GITHUB_ENV
            echo "$CYPRESS_DEFAULT"
            echo "TAG=tag:stable:ci" >> $GITHUB_OUTPUT
            echo "$TAG"
          elif [[ $workflow_name == *"automatic"* || $workflow_name == *"scheduled"* ]]; then
            echo "This is an automatic or scheduled workflow"
            echo "CYPRESS_BRB=op://cy-dev-brb/cypress/CYPRESS_BRB" >> $GITHUB_ENV
            echo "$CYPRESS_BRB"
            echo "CYPRESS_NBC=op://cy-dev-nbc/cypress/CYPRESS_NBC" >> $GITHUB_ENV
            echo "$CYPRESS_NBC"
            echo "CYPRESS_DEFAULT=op://cy-dev-dbc/cypress/CYPRESS_DEFAULT" >> $GITHUB_ENV
            echo "$CYPRESS_DEFAULT"
            echo "TAG=tag:stable:ci" >> $GITHUB_OUTPUT
            echo "$TAG"
          else
            echo "This is an remote workflow"
            echo "CYPRESS_BRB=${{ inputs.cypress_brb }}" >> $GITHUB_ENV
            echo "$CYPRESS_BRB"
            echo "CYPRESS_NBC=${{ inputs.cypress_nbc }}" >> $GITHUB_ENV
            echo "$CYPRESS_NBC"
            echo "CYPRESS_DEFAULT=${{ inputs.cypress_default }}" >> $GITHUB_ENV
            echo "$CYPRESS_DEFAULT"
            echo "TAG=tag:stable:pr:ci" >> $GITHUB_OUTPUT
            echo "$TAG"
            fi

      - name: Set Environment Variables
        run: |
          chmod +x ${{ github.workspace }}/e2e-system-tests/scripts/set-env-vars.sh
          ${{ github.workspace }}/e2e-system-tests/scripts/set-env-vars.sh

      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true

  run-tests:
    runs-on: ubuntu-latest
    needs: configure-load-secrets
    container:
     image: cypress/browsers:node-20.6.1-chrome-116.0.5845.187-1-ff-117.0-edge-116.0.1938.76-1
     options: --user 1001
    outputs:
      tag: ${{ needs.configure-load-secrets.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: hpi-schul-cloud/e2e-system-tests
          path: e2e-system-tests

      - name: Clean up previous report
        uses: cypress-io/github-action@v5
        with:
          working-directory: e2e-system-tests
          command: npm run pretest

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: e2e-system-tests
          command: npm run ${{ needs.configure-load-secrets.outputs.tag }}
          browser: chrome
        env:
          CYPRESS_BRB: ${{ env.CYPRESS_BRB }}
          CYPRESS_NBC: ${{ env.CYPRESS_NBC }}
          CYPRESS_DEFAULT: ${{ env.CYPRESS_DEFAULT }}
          CYPRESS_TEACHER_1_BRB_EMAIL: ${{ env.CYPRESS_TEACHER_1_BRB_EMAIL }}
          CYPRESS_TEACHER_1_BRB_PASSWORD: ${{ env.CYPRESS_TEACHER_1_BRB_PASSWORD }}
          CYPRESS_TEACHER_1_BRB_FIRST_NAME: ${{ env.CYPRESS_TEACHER_1_BRB_FIRST_NAME }}
          CYPRESS_TEACHER_1_BRB_LAST_NAME: ${{ env.CYPRESS_TEACHER_1_BRB_LAST_NAME }}
          CYPRESS_TEACHER_2_BRB_EMAIL: ${{ env.CYPRESS_TEACHER_2_BRB_EMAIL }}
          CYPRESS_TEACHER_2_BRB_PASSWORD: ${{ env.CYPRESS_TEACHER_2_BRB_PASSWORD }}
          CYPRESS_TEACHER_2_BRB_FIRST_NAME: ${{ env.CYPRESS_TEACHER_2_BRB_FIRST_NAME }}
          CYPRESS_TEACHER_2_BRB_LAST_NAME: ${{ env.CYPRESS_TEACHER_2_BRB_LAST_NAME }}
          CYPRESS_TEACHER_1_DBC_EMAIL: ${{ env.CYPRESS_TEACHER_1_DBC_EMAIL }}
          CYPRESS_TEACHER_1_DBC_PASSWORD: ${{ env.CYPRESS_TEACHER_1_DBC_PASSWORD }}
          CYPRESS_TEACHER_1_DBC_FIRST_NAME: ${{ env.CYPRESS_TEACHER_1_DBC_FIRST_NAME }}
          CYPRESS_TEACHER_1_DBC_LAST_NAME: ${{ env.CYPRESS_TEACHER_1_DBC_LAST_NAME }}
          CYPRESS_TEACHER_2_DBC_EMAIL: ${{ env.CYPRESS_TEACHER_2_DBC_EMAIL }}
          CYPRESS_TEACHER_2_DBC_PASSWORD: ${{ env.CYPRESS_TEACHER_2_DBC_PASSWORD }}
          CYPRESS_TEACHER_2_DBC_FIRST_NAME: ${{ env.CYPRESS_TEACHER_2_DBC_FIRST_NAME }}
          CYPRESS_TEACHER_2_DBC_LAST_NAME: ${{ env.CYPRESS_TEACHER_2_DBC_LAST_NAME }}
          CYPRESS_TEACHER_1_NBC_EMAIL: ${{ env.CYPRESS_TEACHER_1_NBC_EMAIL }}
          CYPRESS_TEACHER_1_NBC_PASSWORD: ${{ env.CYPRESS_TEACHER_1_NBC_PASSWORD }}
          CYPRESS_TEACHER_1_NBC_FIRST_NAME: ${{ env.CYPRESS_TEACHER_1_NBC_FIRST_NAME }}
          CYPRESS_TEACHER_1_NBC_LAST_NAME: ${{ env.CYPRESS_TEACHER_1_NBC_LAST_NAME }}
          CYPRESS_TEACHER_2_NBC_EMAIL: ${{ env.CYPRESS_TEACHER_2_NBC_EMAIL }}
          CYPRESS_TEACHER_2_NBC_PASSWORD: ${{ env.CYPRESS_TEACHER_2_NBC_PASSWORD }}
          CYPRESS_TEACHER_2_NBC_FIRST_NAME: ${{ env.CYPRESS_TEACHER_2_NBC_FIRST_NAME }}
          CYPRESS_TEACHER_2_NBC_LAST_NAME: ${{ env.CYPRESS_TEACHER_2_NBC_LAST_NAME }}
          CYPRESS_STUDENT_1_BRB_EMAIL: ${{ env.CYPRESS_STUDENT_1_BRB_EMAIL }}
          CYPRESS_STUDENT_1_BRB_PASSWORD: ${{ env.CYPRESS_STUDENT_1_BRB_PASSWORD }}
          CYPRESS_STUDENT_2_BRB_EMAIL: ${{ env.CYPRESS_STUDENT_2_BRB_EMAIL }}
          CYPRESS_STUDENT_2_BRB_PASSWORD: ${{ env.CYPRESS_STUDENT_2_BRB_PASSWORD }}
          CYPRESS_STUDENT_1_DBC_EMAIL: ${{ env.CYPRESS_STUDENT_1_DBC_EMAIL }}
          CYPRESS_STUDENT_1_DBC_PASSWORD: ${{ env.CYPRESS_STUDENT_1_DBC_PASSWORD }}
          CYPRESS_STUDENT_2_DBC_EMAIL: ${{ env.CYPRESS_STUDENT_2_DBC_EMAIL }}
          CYPRESS_STUDENT_2_DBC_PASSWORD: ${{ env.CYPRESS_STUDENT_2_DBC_PASSWORD }}
          CYPRESS_STUDENT_1_NBC_EMAIL: ${{ env.CYPRESS_STUDENT_1_NBC_EMAIL }}
          CYPRESS_STUDENT_1_NBC_PASSWORD: ${{ env.CYPRESS_STUDENT_1_NBC_PASSWORD }}
          CYPRESS_STUDENT_2_NBC_EMAIL: ${{ env.CYPRESS_STUDENT_2_NBC_EMAIL }}
          CYPRESS_STUDENT_2_NBC_PASSWORD: ${{ env.CYPRESS_STUDENT_2_NBC_PASSWORD }}
          CYPRESS_ADMIN_1_BRB_EMAIL: ${{ env.CYPRESS_ADMIN_1_BRB_EMAIL }}
          CYPRESS_ADMIN_1_BRB_PASSWORD: ${{ env.CYPRESS_ADMIN_1_BRB_PASSWORD }}
          CYPRESS_ADMIN_1_DBC_EMAIL: ${{ env.CYPRESS_ADMIN_1_DBC_EMAIL }}
          CYPRESS_ADMIN_1_DBC_PASSWORD: ${{ env.CYPRESS_ADMIN_1_DBC_PASSWORD }}
          CYPRESS_ADMIN_1_NBC_EMAIL: ${{ env.CYPRESS_ADMIN_1_NBC_EMAIL }}
          CYPRESS_ADMIN_1_NBC_PASSWORD: ${{ env.CYPRESS_ADMIN_1_NBC_PASSWORD }}
          CYPRESS_EXPERT_1_BRB_EMAIL: ${{ env.CYPRESS_EXPERT_1_BRB_EMAIL }}
          CYPRESS_EXPERT_1_BRB_PASSWORD: ${{ env.CYPRESS_EXPERT_1_BRB_PASSWORD }}
          CYPRESS_EXPERT_1_DBC_EMAIL: ${{ env.CYPRESS_EXPERT_1_DBC_EMAIL }}
          CYPRESS_EXPERT_1_DBC_PASSWORD: ${{ env.CYPRESS_EXPERT_1_DBC_PASSWORD }}
          CYPRESS_EXPERT_1_NBC_EMAIL: ${{ env.CYPRESS_EXPERT_1_NBC_EMAIL }}
          CYPRESS_EXPERT_1_NBC_PASSWORD: ${{ env.CYPRESS_EXPERT_1_NBC_PASSWORD }}
          CYPRESS_STUDENT_BRB_EXTERN: ${{ env.CYPRESS_STUDENT_BRB_EXTERN }}
          CYPRESS_STUDENT_BRB_EXTERN_PASSWORD: ${{ env.CYPRESS_STUDENT_BRB_EXTERN_PASSWORD }}
          CYPRESS_STUDENT_DBC_EXTERN: ${{ env.CYPRESS_STUDENT_DBC_EXTERN }}
          CYPRESS_STUDENT_DBC_EXTERN_PASSWORD: ${{ env.CYPRESS_STUDENT_DBC_EXTERN_PASSWORD }}
          CYPRESS_STUDENT_NBC_EXTERN: ${{ env.CYPRESS_STUDENT_NBC_EXTERN }}
          CYPRESS_STUDENT_NBC_EXTERN_PASSWORD: ${{ env.CYPRESS_STUDENT_NBC_EXTERN_PASSWORD }}
          CYPRESS_STUDENT_BRB_PASSWORD_CHANGE_EMAIL: ${{ env.CYPRESS_STUDENT_BRB_PASSWORD_CHANGE_EMAIL }}
          CYPRESS_STUDENT_BRB_PASSWORD_CHANGE_OLD_PWD: ${{ env.CYPRESS_STUDENT_BRB_PASSWORD_CHANGE_OLD_PWD }}
          CYPRESS_STUDENT_BRB_PASSWORD_CHANGE_NEW_PWD: ${{ env.CYPRESS_STUDENT_BRB_PASSWORD_CHANGE_NEW_PWD }}
          CYPRESS_STUDENT_DBC_PASSWORD_CHANGE_EMAIL: ${{ env.CYPRESS_STUDENT_DBC_PASSWORD_CHANGE_EMAIL }}
          CYPRESS_STUDENT_DBC_PASSWORD_CHANGE_OLD_PWD: ${{ env.CYPRESS_STUDENT_DBC_PASSWORD_CHANGE_OLD_PWD }}
          CYPRESS_STUDENT_DBC_PASSWORD_CHANGE_NEW_PWD: ${{ env.CYPRESS_STUDENT_DBC_PASSWORD_CHANGE_NEW_PWD }}
          CYPRESS_STUDENT_NBC_PASSWORD_CHANGE_EMAIL: ${{ env.CYPRESS_STUDENT_NBC_PASSWORD_CHANGE_EMAIL }}
          CYPRESS_STUDENT_NBC_PASSWORD_CHANGE_OLD_PWD: ${{ env.CYPRESS_STUDENT_NBC_PASSWORD_CHANGE_OLD_PWD }}
          CYPRESS_STUDENT_NBC_PASSWORD_CHANGE_NEW_PWD: ${{ env.CYPRESS_STUDENT_NBC_PASSWORD_CHANGE_NEW_PWD }}
          DEBUG: "@cypress/github-action"

      - name: Generate Report
        if: always()
        working-directory: e2e-system-tests
        run: |
          npm run generate:report

      - name: Upload Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: my-report
          path: ${{ github.workspace }}/e2e-system-tests/reports/

      - name: Upload Video Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: my-video-artifact
          path: ${{ github.workspace }}/e2e-system-tests/cypress/videos/
          retention-days: 3
