name: configure, load secrets, run Cypress tests, generate and upload reports
on:
  workflow_call:
    secrets:
      service-account-token:
        required: true
    inputs:
      cypress_brb:
        description: "brb url from remote workflow"
        type: string
      cypress_nbc:
        description: "nbc url from remote workflow"
        type: string
      cypress_default:
        description: "default url from remote workflow"
        type: string

jobs:
  configure-load-secrets-and-run_tests:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.setting_url.outputs.TAG }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: hpi-schul-cloud/e2e-system-tests
          path: e2e-system-tests

      - name: Configure 1Password Service Account
        uses: 1password/load-secrets-action/configure@v1
        with:
          service-account-token: ${{ secrets.service-account-token }}

      - name: Setting URL's
        id: setting_url
        run: |
          workflow_name="${{ github.workflow }}"
          if [[ $workflow_name == *"manual"* ]]; then
            echo "This is a manual workflow"
            echo "CYPRESS_BRB=${{ github.event.inputs.instance1 }}" >> $GITHUB_ENV
            echo "$CYPRESS_BRB"
            echo "CYPRESS_NBC=${{ github.event.inputs.instance2 }}" >> $GITHUB_ENV
            echo "$CYPRESS_NBC"
            echo "CYPRESS_DEFAULT=${{ github.event.inputs.instance3 }}" >> $GITHUB_ENV
            echo "$CYPRESS_DEFAULT"
            echo "TAG=tag:stable:ci" >> $GITHUB_OUTPUT
            echo "$TAG"
          elif [[ $workflow_name == *"automatic"* || $workflow_name == *"scheduled"* ]]; then
            echo "This is an automatic or scheduled workflow"
            echo "CYPRESS_BRB=op://cy-dev-brb/cypress/CYPRESS_BRB" >> $GITHUB_ENV
            echo "$CYPRESS_BRB"
            echo "CYPRESS_NBC=op://cy-dev-nbc/cypress/CYPRESS_NBC" >> $GITHUB_ENV
            echo "$CYPRESS_NBC"
            echo "CYPRESS_DEFAULT=op://cy-dev-dbc/cypress/CYPRESS_DEFAULT" >> $GITHUB_ENV
            echo "$CYPRESS_DEFAULT"
            echo "TAG=tag:stable:ci" >> $GITHUB_OUTPUT
            echo "$TAG"
          else
            echo "This is an remote workflow"
            echo "CYPRESS_BRB=${{ inputs.cypress_brb }}" >> $GITHUB_ENV
            echo "$CYPRESS_BRB"
            echo "CYPRESS_NBC=${{ inputs.cypress_nbc }}" >> $GITHUB_ENV
            echo "$CYPRESS_NBC"
            echo "CYPRESS_DEFAULT=${{ inputs.cypress_default }}" >> $GITHUB_ENV
            echo "$CYPRESS_DEFAULT"
            echo "TAG=tag:stable:pr:ci" >> $GITHUB_OUTPUT
            echo "$TAG"
            fi

      - name: Set Environment Variables
        run: |
          chmod +x ${{ github.workspace }}/e2e-system-tests/scripts/set-env-vars.sh
          ${{ github.workspace }}/e2e-system-tests/scripts/set-env-vars.sh

      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true

      - name: Clean up previous report
        uses: cypress-io/github-action@v5
        with:
          working-directory: e2e-system-tests
          command: npm run pretest

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: e2e-system-tests
          command: npm run ${{ steps.setting_url.outputs.tag }}
          browser: chrome
          headed: true
        env:
          DEBUG: "@cypress/github-action"

      - name: Generate Report
        if: always()
        working-directory: e2e-system-tests
        run: |
          npm run generate:report

      - name: Upload Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: my-report
          path: ${{ github.workspace }}/e2e-system-tests/reports/

      - name: Upload Video Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: my-video-artifact
          path: ${{ github.workspace }}/e2e-system-tests/cypress/videos/
          retention-days: 3
