name: e2e-manual-trigger-tests
on:
  workflow_dispatch:
    inputs:
      instance1:
        description: "Please enter a valid BRB instance URL to run the tests on"
        default: "https://brb-main.cd.dbildungscloud.dev"
        required: true
      instance2:
        description: "Please enter a valid NBC instance URL to run the tests on"
        default: "https://nbc-main.cd.dbildungscloud.dev"
        required: true
      instance3:
        description: "Please enter a valid DEFAULT instance URL to run the tests on"
        default: "https://default-main.cd.dbildungscloud.dev"
        required: true

jobs:
  e2e-system-tests:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set_variables.outputs.environment }}

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set all parameters for next job
        id: set_variables
        shell: bash
        run: |

          if [[ ! ${{ inputs.instance1 }} =~ (staging|schulportal) && ! ${{ inputs.instance2 }} =~ (staging|schulportal) && ! ${{ inputs.instance3 }} =~ (staging|schulportal) ]]; then
              echo "environment=dev" >> $GITHUB_OUTPUT
          else
              echo "environment=ref" >> $GITHUB_OUTPUT
          fi

  configuring-loading-secrets-running-tests:
    needs: e2e-system-tests
    uses: ./.github/workflows/main.yml
    secrets:
      service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}
    with:
      cypress_brb: ${{ inputs.instance1 }}
      cypress_default: ${{ inputs.instance3 }}
      cypress_nbc: ${{ inputs.instance2 }}
      tag: tag:stable:ci
      environment: ${{ needs.e2e-system-tests.outputs.environment }}

  notify_RC:
    runs-on: ubuntu-latest
    needs:
      - e2e-system-tests
      - configuring-loading-secrets-running-tests
    if: |
      always()

    steps:
      - uses: technote-space/workflow-conclusion-action@v3

      - name: Send Notification to Rocket Chat
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
        with:
          type: ${{ env.WORKFLOW_CONCLUSION }}
          job_name: "Cypress Tests"
          url: ${{ secrets.RC_WEBHOOK_URL }}
          username: Manual Trigger Test Run
