name: e2e-manual-trigger-tests
on:
  workflow_dispatch:
    inputs:
      instance1:
        description: 'Please enter a valid BRB instance URL to run the tests on'
        default: 'https://brb-main.cd.dbildungscloud.dev/'
        required: true
      instance2:
        description: 'Please enter a valid NBC instance URL to run the tests on'
        default: 'https://nbc-main.cd.dbildungscloud.dev/'
        required: true
      instance3:
        description: 'Please enter a valid DEFAULT instance URL to run the tests on'
        default: 'https://default-main.cd.dbildungscloud.dev/'
        required: true

jobs:
  e2e-system-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        spec:
          [
            'help',
            'management',
            'dashboard',
            'news',
            'courses',
            'account',
            'addons',
            'login',
            'tasks',
            'team',
          ]

    steps:
      - name: 🔔🔔🔔 Checkout 🔔🔔🔔
        uses: actions/checkout@v3

      - name: 🗑 Clean up previous report 🗑
        uses: cypress-io/github-action@v4
        with:
          command: npm run pretest

      - name: 🧪 Cypress run 🧪
        uses: cypress-io/github-action@v4
        env:
          CYPRESS_BRB: ${{ github.event.inputs.instance1 }}
          CYPRESS_NBC: ${{ github.event.inputs.instance2 }}
          CYPRESS_DEFAULT: ${{ github.event.inputs.instance3 }}
          CYPRESS_TEACHER_1_EMAIL: ${{ secrets.CYPRESS_TEACHER_1_EMAIL }}
          CYPRESS_TEACHER_1_PASSWORD: ${{ secrets.CYPRESS_TEACHER_1_PASSWORD }}
          CYPRESS_TEACHER_2_EMAIL: ${{ secrets.CYPRESS_TEACHER_2_EMAIL }}
          CYPRESS_TEACHER_2_PASSWORD: ${{ secrets.CYPRESS_TEACHER_2_PASSWORD }}
          CYPRESS_STUDENT_1_EMAIL: ${{ secrets.CYPRESS_STUDENT_1_EMAIL }}
          CYPRESS_STUDENT_1_PASSWORD: ${{ secrets.CYPRESS_STUDENT_1_PASSWORD }}
          CYPRESS_STUDENT_2_EMAIL: ${{ secrets.CYPRESS_STUDENT_2_EMAIL }}
          CYPRESS_STUDENT_2_PASSWORD: ${{ secrets.CYPRESS_STUDENT_2_PASSWORD }}
          CYPRESS_ADMIN_1_EMAIL: ${{ secrets.CYPRESS_ADMIN_1_EMAIL }}
          CYPRESS_ADMIN_1_PASSWORD: ${{ secrets.CYPRESS_ADMIN_1_PASSWORD }}
          CYPRESS_EXPERT_1_EMAIL: ${{ secrets.CYPRESS_EXPERT_1_EMAIL }}
          CYPRESS_EXPERT_1_PASSWORD": ${{ secrets.CYPRESS_EXPERT_1_PASSWORD }}
          CYPRESS_STUDENT_EXTERN: ${{ secrets.CYPRESS_STUDENT_EXTERN }}
          CYPRESS_STUDENT_EXTERN_PASSWORD: ${{ secrets.CYPRESS_STUDENT_EXTERN_PASSWORD }}
        with:
          browser: chrome
          headed: false
          command: npm run tag:stable:${{ matrix.spec }}

      - name: 📬 Upload test artifacts 📬
        uses: actions/upload-artifact@v3
        if: always()
        with:
          if-no-files-found: error
          name: artifacts
          path: |
            ${{ github.workspace }}/cypress/cucumber-json/
            ${{ github.workspace }}/cypress/.run/
            ${{ github.workspace }}/cypress/videos/features
            ${{ github.workspace }}/cypress/screenshots

  generate-and-upload-report:
    runs-on: ubuntu-latest
    needs: e2e-system-tests
    if: always()

    steps:
      - name: 🔔🔔🔔 Checkout 🔔🔔🔔
        uses: actions/checkout@v3

      - name: 📩 Download reports artifacts 📩
        uses: actions/download-artifact@v3
        if: always()
        with:
          name: artifacts
          path: ${{ github.workspace }}/cypress/

      - name: 🚀 Generate Report 🚀
        uses: cypress-io/github-action@v4
        if: always()
        with:
          command: npm run generate:report

      - name: 🎉 Upload Report 🎉
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: my-report
          path: ${{ github.workspace }}/cypress/reports

      - name: 📼 Upload Video Artifact 📼
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: my-video-artifact
          path: ${{ github.workspace }}/cypress/videos/features
          retention-days: 3

  notify_RC:
    runs-on: ubuntu-latest
    needs: [e2e-system-tests, generate-and-upload-report]
    if: |
      always()

    steps:
      - name: 🚀 Send Notification to Rocket Chat 🚀
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
        if: always()
        with:
          type: ${{ job.status }}
          job_name: 'Cypress Tests'
          url: ${{ secrets.RC_WEBHOOK_URL }}
          username: Scheduled Automated Test Run
