name: e2e-scheduled-trigger-tests
on: [push]
jobs:
  e2e-system-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        spec: ['help']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Cypress run
        uses: cypress-io/github-action@v4
        env:
          CYPRESS_BRB: ${{ secrets.CYPRESS_BRB }}
          CYPRESS_NBC: ${{ secrets.CYPRESS_NBC }}
          CYPRESS_DEFAULT: ${{ secrets.CYPRESS_DEFAULT }}
          CYPRESS_TEACHER_1_EMAIL: ${{ secrets.CYPRESS_TEACHER_1_EMAIL }}
          CYPRESS_TEACHER_1_PASSWORD: ${{ secrets.CYPRESS_TEACHER_1_PASSWORD }}
          CYPRESS_TEACHER_2_EMAIL: ${{ secrets.CYPRESS_TEACHER_2_EMAIL }}
          CYPRESS_TEACHER_2_PASSWORD: ${{ secrets.CYPRESS_TEACHER_2_PASSWORD }}
          CYPRESS_STUDENT_1_EMAIL: ${{ secrets.CYPRESS_STUDENT_1_EMAIL }}
          CYPRESS_STUDENT_1_PASSWORD: ${{ secrets.CYPRESS_STUDENT_1_PASSWORD }}
          CYPRESS_STUDENT_2_EMAIL: ${{ secrets.CYPRESS_STUDENT_2_EMAIL }}
          CYPRESS_STUDENT_2_PASSWORD: ${{ secrets.CYPRESS_STUDENT_2_PASSWORD }}
          CYPRESS_ADMIN_1_EMAIL: ${{ secrets.CYPRESS_ADMIN_1_EMAIL }}
          CYPRESS_ADMIN_1_PASSWORD: ${{ secrets.CYPRESS_ADMIN_1_PASSWORD }}
          CYPRESS_EXPERT_1_EMAIL: ${{ secrets.CYPRESS_EXPERT_1_EMAIL }}
          CYPRESS_EXPERT_1_PASSWORD": ${{ secrets.CYPRESS_EXPERT_1_PASSWORD }}
          CYPRESS_STUDENT_EXTERN: ${{ secrets.CYPRESS_STUDENT_EXTERN }}
          CYPRESS_STUDENT_EXTERN_PASSWORD: ${{ secrets.CYPRESS_STUDENT_EXTERN_PASSWORD }}
        with:
          browser: chrome
          headed: false
          command: npm run tag:${{ matrix.spec }}

      - name: Upload test artifacts (cucumber-json)
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cucumber-json
          path:
            /home/runner/work/e2e-system-tests/e2e-system-tests/cucumber-json

      - name: Upload test artifacts (.run)
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: run
          path:
            /home/runner/work/e2e-system-tests/e2e-system-tests/.run

  generate-and-upload-report:
    runs-on: ubuntu-latest
    needs: e2e-system-tests
    if: always()

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download reports artifacts (cucumber-json)
        uses: actions/download-artifact@v3
        if: always()
        with:
          name: cucumber-json

      - name: Download reports artifacts (.run)
        uses: actions/download-artifact@v3
        if: always()
        with:
          name: run

      - name: Generate Report
        uses: cypress-io/github-action@v4
        if: always()
        with:
          command: npm run generate:report

      - name: Upload Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: my-report
          path: /home/runner/work/e2e-system-tests/e2e-system-tests/cypress/reports

      - name: Upload Video Artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: my-video-artifact
          path: /home/runner/work/e2e-system-tests/e2e-system-tests/cypress/videos/features
          retention-days: 3
