name: e2e-remote-trigger-tests
on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  e2e-system-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: check local branch
        id: check_branch
        run: |
          check_cypress_branch=$(git ls-remote --heads "https://github.com/hpi-schul-cloud/e2e-system-tests.git" ${{ inputs.ref }})
          if [[ -z ${check_cypress_branch} ]]; then
            echo "LOCAL_BRANCH_EXISTS=false" >> "$GITHUB_OUTPUT"
          else
            echo "LOCAL_BRANCH_EXISTS=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout main
        if: steps.check_branch.outputs.LOCAL_BRANCH_EXISTS == 'false'
        uses: actions/checkout@v3
        with:
          repository: hpi-schul-cloud/e2e-system-tests
          path: e2e-system-tests

      - name: Checkout branch
        if: steps.check_branch.outputs.LOCAL_BRANCH_EXISTS == 'true'
        uses: actions/checkout@v3
        with:
          repository: hpi-schul-cloud/e2e-system-tests
          ref: ${{ inputs.ref }}
          path: e2e-system-tests

      - name: Set target
        shell: bash
        run: |
          branch_name=${{ inputs.ref }}

          # This cleaning of the branch name needs to be done the same way as in deployment. 
          # Currently done in https://github.com/hpi-schul-cloud/dof_app_deploy/blob/main/.github/workflows/clean_workflow.yml
          cleaned_branch_name=$(echo $branch_name | sed 's@.*/@@' | tr [A-Z] [a-z] | tr _ - | tr \. -)
          echo "cleaned branch name: $cleaned_branch_name"

          echo "CYPRESS_BRB=https://brb-${cleaned_branch_name}.cd.dbildungscloud.dev" >> $GITHUB_ENV
          echo "CYPRESS_NBC=https://nbc-${cleaned_branch_name}.cd.dbildungscloud.dev" >> $GITHUB_ENV
          echo "CYPRESS_DEFAULT=https://default-${cleaned_branch_name}.cd.dbildungscloud.dev" >> $GITHUB_ENV

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: e2e-system-tests
          command: npm run tag:stable:pr
        env:
          CYPRESS_TEACHER_1_EMAIL: ${{ secrets.CYPRESS_TEACHER_1_EMAIL }}
          CYPRESS_TEACHER_1_PASSWORD: ${{ secrets.CYPRESS_TEACHER_1_PASSWORD }}
          CYPRESS_TEACHER_2_EMAIL: ${{ secrets.CYPRESS_TEACHER_2_EMAIL }}
          CYPRESS_TEACHER_2_PASSWORD: ${{ secrets.CYPRESS_TEACHER_2_PASSWORD }}
          CYPRESS_STUDENT_1_EMAIL: ${{ secrets.CYPRESS_STUDENT_1_EMAIL }}
          CYPRESS_STUDENT_1_PASSWORD: ${{ secrets.CYPRESS_STUDENT_1_PASSWORD }}
          CYPRESS_STUDENT_2_EMAIL: ${{ secrets.CYPRESS_STUDENT_2_EMAIL }}
          CYPRESS_STUDENT_2_PASSWORD: ${{ secrets.CYPRESS_STUDENT_2_PASSWORD }}
          CYPRESS_ADMIN_1_EMAIL: ${{ secrets.CYPRESS_ADMIN_1_EMAIL }}
          CYPRESS_ADMIN_1_PASSWORD: ${{ secrets.CYPRESS_ADMIN_1_PASSWORD }}
          CYPRESS_EXPERT_1_EMAIL: ${{ secrets.CYPRESS_EXPERT_1_EMAIL }}
          CYPRESS_EXPERT_1_PASSWORD": ${{ secrets.CYPRESS_EXPERT_1_PASSWORD }}
          CYPRESS_STUDENT_EXTERN: ${{ secrets.CYPRESS_STUDENT_EXTERN }}
          CYPRESS_STUDENT_EXTERN_PASSWORD: ${{ secrets.CYPRESS_STUDENT_EXTERN_PASSWORD }}
          CYPRESS_STUDENT_PASSWORD_CHANGE_EMAIL: ${{ secrets.CYPRESS_STUDENT_PASSWORD_CHANGE_EMAIL }}
          CYPRESS_STUDENT_PASSWORD_CHANGE_OLD_PWD: ${{ secrets.CYPRESS_STUDENT_PASSWORD_CHANGE_OLD_PWD }}
          CYPRESS_STUDENT_PASSWORD_CHANGE_NEW_PWD: ${{ secrets.CYPRESS_STUDENT_PASSWORD_CHANGE_NEW_PWD }}
          CYPRESS_TEACHER_1_FIRST_NAME: ${{ secrets.CYPRESS_TEACHER_1_FIRST_NAME }}
          CYPRESS_TEACHER_1_LAST_NAME: ${{ secrets.CYPRESS_TEACHER_1_LAST_NAME }}
          CYPRESS_TEACHER_2_FIRST_NAME: ${{ secrets.CYPRESS_TEACHER_2_FIRST_NAME }}
          CYPRESS_TEACHER_2_LAST_NAME: ${{ secrets.CYPRESS_TEACHER_2_LAST_NAME }}
          DEBUG: '@cypress/github-action'

      - name: Generate Report
        uses: cypress-io/github-action@v5
        if: always()
        with:
          working-directory: e2e-system-tests
          command: npm run generate:report

      - name: Upload Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: my-report
          path: e2e-system-tests/reports

      - name: Upload Video Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: my-video-artifact
          path: e2e-system-tests/cypress/videos/
          retention-days: 3