# This is a basic workflow to help you get started with Actions

name: e2e-tests
on:  [push]
jobs:
 cypress-run:
    runs-on: ubuntu-20.04
    steps:
     - name: Checkout
     - uses: actions/checkout@v2
     - name: Cypress run
     - uses: cypress-io/github-action@v2


