# This is a basic workflow to help you get started with Actions

name: e2e-tests
on:  [push]
jobs:
 e2e-tests:
    runs-on: ubuntu-20.04
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: npm ci
       run: npm ci --prefer-offline --no-audit
     - name: Cypress run
       run: npm run cy:run

     - name: 'Upload Artifact'
       uses: actions/upload-artifact@v2
       with:
         name: my-artifact
         path: /home/runner/work/e2e-system-tests/e2e-system-tests/cypress/videos/features
         retention-days: 3

     - name: 'Download artifact'
       uses: actions/download-artifact@v2
       with:
         name: 'my-artifact'
         path: /home/runner/work/e2e-system-tests/e2e-system-tests/cypress/videos/features